# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20160412_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pub_date',
            new_name='create_date',
        ),
    ]
