# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438')),
                ('desc', models.TextField(blank=True, max_length=300, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='magazine.Category', verbose_name='\u0420\u043e\u0434\u0438\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f',
                'verbose_name_plural': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u0418\u043c\u044f')),
                ('subject', models.CharField(max_length=150, verbose_name='\u0422\u0435\u043c\u0430 \u043f\u0438\u0441\u044c\u043c\u0430')),
                ('email', models.EmailField(max_length=254, verbose_name='\u041f\u043e\u0447\u0442\u0430')),
                ('phone', models.CharField(blank=True, max_length=14, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430')),
                ('text', models.TextField(max_length=1000, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u0438\u0441\u044c\u043c\u0430')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0438\u043d\u0435\u043d\u0438\u044f')),
                ('status', models.CharField(choices=[('N', '\u041d\u043e\u0432\u043e\u0435'), ('T', '\u041e\u0431\u0440\u0430\u0431\u043e\u0442\u0430\u043d\u043d\u043e\u0435')], default='N', max_length=1, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
            ],
            options={
                'verbose_name': '\u041f\u0438\u0441\u044c\u043c\u043e',
                'verbose_name_plural': '\u041f\u0438\u0441\u044c\u043c\u0430',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100, verbose_name='\u0418\u043c\u044f \u0437\u0430\u043a\u0430\u0437\u0447\u0438\u043a\u0430')),
                ('phone', models.CharField(max_length=14, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='\u041f\u043e\u0447\u0442\u0430')),
                ('status', models.CharField(choices=[('N', '\u041d\u043e\u0432\u044b\u0439'), ('R', '\u041e\u0442\u043a\u0430\u0437'), ('T', '\u041e\u0431\u0440\u0430\u0431\u043e\u0442\u0430\u043d\u043d\u044b\u0439')], default='N', max_length=1, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u0437\u0430\u043a\u0430\u0437\u0430')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f')),
                ('text', models.CharField(blank=True, max_length=300, verbose_name='\u0414\u043e\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u0435')),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name': '\u0417\u0430\u043a\u0430\u0437',
                'verbose_name_plural': '\u0417\u0430\u043a\u0430\u0437\u044b',
            },
        ),
        migrations.CreateModel(
            name='OrderPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u0426\u0435\u043d\u0430')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u0426\u0435\u043d\u0430 \u0441\u043e \u0441\u043a\u0438\u0434\u043a\u043e\u0439')),
                ('count', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='magazine.Order')),
            ],
            options={
                'ordering': ['-count'],
                'verbose_name': 'Order position',
                'verbose_name_plural': 'Order Positions',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=30, null=True, unique=True, verbose_name='\u041a\u043e\u0434 \u0442\u043e\u0432\u0430\u0440\u0430')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('full_desc', models.TextField(verbose_name='\u041f\u043e\u043b\u043d\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f')),
                ('count', models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('img', models.ImageField(blank=True, upload_to='images/products/%Y/%m/%d', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('status', models.CharField(choices=[('S', '\u0412 \u043d\u0430\u043b\u0438\u0447\u0438\u0438'), ('N', '\u041d\u0435\u0442 \u0432 \u043f\u0440\u043e\u0434\u0430\u0436\u0435'), ('O', '\u041f\u043e\u0434 \u0437\u0430\u043a\u0430\u0437')], default='O', max_length=1, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u0426\u0435\u043d\u0430')),
                ('discount', models.PositiveIntegerField(blank=True, default=0, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazine.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0422\u043e\u0432\u0430\u0440',
                'verbose_name_plural': '\u0422\u043e\u0432\u0430\u0440\u044b',
            },
        ),
        migrations.AddField(
            model_name='orderposition',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='magazine.Product'),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set([('id', 'slug')]),
        ),
    ]
