# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_auto_20160407_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd1\x81\xd0\xbe\xd0\xb7\xd0\xb4\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f \xd0\xbe\xd1\x82\xd0\xb7\xd1\x8b\xd0\xb2\xd0\xb0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xb8\xd0\xb7\xd0\xbc\xd0\xb8\xd0\xbd\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f \xd0\xbe\xd1\x82\xd0\xb7\xd1\x8b\xd0\xb2\xd0\xb0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[(b'N', b'\xd0\x9d\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb9'), (b'F', b'\xd0\x9e\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb1\xd0\xbe\xd1\x82\xd0\xb0\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb9')], default=b'F', max_length=1, verbose_name=b'\xd0\xa1\xd1\x82\xd0\xb0\xd1\x82\xd1\x83\xd1\x81 \xd0\xbe\xd1\x82\xd0\xb7\xd1\x8b\xd0\xb2\xd0\xb0'),
        ),
        migrations.AddField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(auto_now=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name=b'slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[(b'Y', b'\xd0\x92 \xd0\xbd\xd0\xb0\xd0\xbb\xd0\xb8\xd1\x87\xd0\xb8\xd0\xb8'), (b'N', b'\xd0\x9d\xd0\xb5\xd1\x82 \xd0\xb2 \xd0\xbd\xd0\xb0\xd0\xbb\xd0\xb8\xd1\x87\xd0\xb8\xd0\xb8'), (b'O', b'\xd0\x9f\xd0\xbe\xd0\xb4 \xd0\xb7\xd0\xb0\xd0\xba\xd0\xb0\xd0\xb7')], default=b'O', max_length=1, verbose_name=b'\xd0\xa1\xd1\x82\xd0\xb0\xd1\x82\xd1\x83\xd1\x81 \xd1\x82\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x80\xd0\xb0'),
        ),
    ]
